gui:
  authorColors:
    'Jan Baer': 'green'
os:
  edit: 'nvim -- {{filename}}'
keybinding:
  universal:
    filteringMenu: <c-f>
  files:
    findBaseCommitForFixup: <c-f>
customCommands:
  - key: '<c-k>'
    context: 'status'
    command: '~/bin/init-keychain.sh'
  - key: '<c-t>'
    context: 'localBranches'
    command: 'git push --tags'
  - key: 'a'
    context: 'files'
    command: "git {{if .SelectedFile.HasUnstagedChanges}} add {{else}} reset {{end}} {{.SelectedFile.Name | quote}}"
    description: 'Toggle file staged'
  - key: 'C'
    context: 'global'
    command: "git commit"
    output: terminal
  - key: '<c-C>'
    context: 'global'
    description: "Create a commit message with using AI"
    command: "lumen draft | wl-copy"
    output: terminal
  - key: 'f'
    context: 'global'
    command: "git fetch"
    output: terminal
  - key: 'n'
    context: 'localBranches'
    prompts:
      - type: 'input'
        title: 'What is the new feature branch name?'
        key: 'BranchName'
        initialValue: ''
    command: "git checkout -b feature/{{.Form.BranchName}}"
    loadingText: 'Creating feature branch'
  - key: '<c-p>'
    context: 'localBranches'
    command: "git push --no-verify --force-with-lease"
    loadingText: "Git pushing without verifying..."
